In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [2]:
df=pd.read_csv("titanic.csv")

In [ ]:
df.info

In [4]:
df["Age"]=df["Age"].fillna(df["Age"].mean())

In [5]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Lname            0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          125
Embarked         1
dtype: int64

In [6]:
grouped_data=df.groupby('Sex')['Age']

In [7]:
summary=grouped_data.describe()

In [8]:
summary

        count       mean        std   min   25%        50%    75%   max
Sex
female   56.0  25.058457  11.903499  2.00  17.0  27.000000  29.25  58.0
male    100.0  29.868017  13.511006  0.83  22.0  28.141508  34.25  71.0

In [23]:
print("mean", df['Age'].mean())
print("median", df['Age'].median())
print("mode", df['Age'].mode())
print("std", df['Age'].std())
print("min", df['Age'].min())

mean 28.141507936507935
median 28.141507936507935
mode 0    28.141508
Name: Age, dtype: float64
std 13.123651589964874
min 0.83

In [9]:
summary_2=grouped_data.agg(['mean','median'])

In [10]:
summary_2

             mean     median
Sex
female  25.058457  27.000000
male    29.868017  28.141508

In [11]:
age_list=grouped_data.apply(list)
age_list

Sex
female    [38.0, 26.0, 35.0, 27.0, 14.0, 4.0, 58.0, 14.0...
male      [22.0, 35.0, 28.141507936507935, 54.0, 2.0, 20...
Name: Age, dtype: object

In [12]:
grouped_data2=df.groupby('Sex')['Fare']
new_summary=grouped_data2.describe()
new_summary

        count       mean        std    min     25%      50%      75%    max
Sex
female   56.0  28.460639  40.144759  7.225  9.7375  15.9250  26.8500  263.0
male    100.0  27.912998  39.180974  6.750  7.9177  12.0125  34.4448  263.0

In [13]:
#IRIS DATASET

In [14]:
df1=pd.read_csv("iris.csv")

In [18]:
grouped_data1=df1.groupby('Species')
summary1=grouped_data1.describe()
summary1

                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [22]:
#can skip 
for spec , data in grouped_data1:
    print("Species=",spec)
    print(data.describe())

Species= Iris-setosa
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000
Species= Iris-versicolor
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000
Species= Iris-virginica
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000

In [20]:
Species_list=grouped_data1.apply(list)
Species_list

Species
Iris-setosa        [Id, SepalLengthCm, SepalWidthCm, PetalLengthC...
Iris-versicolor    [Id, SepalLengthCm, SepalWidthCm, PetalLengthC...
Iris-virginica     [Id, SepalLengthCm, SepalWidthCm, PetalLengthC...
dtype: object